import type Redis from "ioredis-rejson";
import iconv from "iconv-lite";
import fs from "node:fs";
import { gfParse } from "./parser";
import { redis } from "$lib/redis";
import { createClient } from "@supabase/supabase-js";
import { PUBLIC_SUPABASE_URL } from "$env/static/public";
import { PRIVATE_SUPABASE_SERVICE_KEY } from "$env/static/private";
import type { Database } from "$lib/supabase";

export type Item = {
	id: number;
	icon_filename: string;
	model_id: string;
	model_filename: string;
	weapon_effect_id: number;
	fly_effect_id: number;
	used_effect_id: number;
	used_sound_name: string;
	enhance_effect_id: number;
	name: string;
	item_type: number;
	equip_type: number;
	op_flags: number;
	op_flags_plus: number;
	target: number;
	restrict_gender: number;
	restrict_level: number;
	restrict_max_level: number;
	rebirth_count: number;
	rebirth_score: number;
	rebirth_max_score: number;
	restrict_align: number;
	restrict_prestige: number;
	restrict_class: string;
	item_quality: string;
	item_group: number;
	casting_time: number;
	cooldown_time: number;
	cooldown_group: number;
	max_hp: number;
	max_mp: number;
	str: number;
	vit: number;
	int: number;
	will: number;
	agi: number;
	avg_physical_damage: number;
	rand_physical_damage: number;
	attack_range: number;
	attack_speed: number;
	attack: number;
	range_attack: number;
	physical_defence: number;
	magic_damage: number;
	magic_defence: number;
	hit_rate: number;
	dodge_rate: number;
	physical_critical_rate: number;
	physical_critical_damage: number;
	magic_critical_rate: number;
	magic_critical_damage: number;
	physical_penetration: number;
	magic_penetration: number;
	physical_penetration_defence: number;
	magic_penetration_defence: number;
	attribute: number;
	attribute_rate: number;
	attribute_damage: number;
	attribute_resist: number;
	special_type: number;
	special_rate: number;
	special_damage: number;
	drop_rate: number;
	drop_index: number;
	treasure_buffs1: number;
	treasure_buffs2: number;
	treasure_buffs3: number;
	treasure_buffs4: number;
	enchant_type: number;
	enchant_id: number;
	expert_level: number;
	expert_enchant_id: number;
	elf_skill_id: number;
	enchant_time_type: number;
	enchant_duration: number;
	limit_type: number;
	due_date_time: number;
	backpack_size: number;
	max_socket: number;
	socket_rate: number;
	max_durability: number;
	max_stack: number;
	shop_price_type: number;
	sys_price: number;
	restrict_event_pos_id: string;
	unknown_string: string;
	block_rate: number;
	log_level: number;
	auction_type: number;
	extra_data1: number;
	extra_data2: number;
	extra_data3: number;
	tip: string;
	name_translation: Record<string, string>;
	tip_translation: Record<string, string>;
};

export const maxDropItem = 45;
export type DropItemData = {
	id: number;
	name: string;
	level: number;
	dropGoldRate: number;
	avgGold: number;
	randGold: number;
	randTimes: number;
	notDropRate: number;
	greenRate: number;
	blueRate: number;
	orangeRate: number;
	yellowRate: number;
	unknown1: number;
	dropItems: DropItem[];
	unknownString: string;
};

export type DropItem = {
	itemId: number;
	itemName: string;
	stack: number;
	rate: number;
};

// let str = iconv.decode(fileData, 'win1252');
